name: Comprimir Archivos en Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compress_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Comprimir archivos cambiados
      run: |
        # Crear un directorio temporal para los archivos comprimidos
        mkdir compressed_files
        
        # Comprimir los archivos modificados en un archivo zip
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | \
        grep -v '^\.github' | \
        while read file; do
          # Copiar cada archivo modificado al directorio temporal
          cp --parents "$file" compressed_files/
        done
        
        # Crear el archivo zip
        zip -r DjangoHexTemplate.zip compressed_files

    - name: Subir el archivo comprimido como artefacto
      uses: actions/upload-artifact@v3
      with:
        name: archivo-comprimido
        path: DjangoHexTemplate.zip


